language: python
python:
  - "2.7"
  - "3.4"
  - "3.3"
env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls
script: coverage run --source='.' manage.py test
after_success: coveralls
